FROM ubuntu

MAINTAINER Juan Casian <jcasian@student.42.us.org>

RUN apt-get update && \
	apt-get upgrade -y && \
	apt-get install -y  python3.6 vim git

CMD bash
# docker build -t bonus-py .
# docker run --rm -t bonus-py
