#!/bin/bash

#run debian and launch commands directly into container
#docker run -it debian /bin/bash
apt-get update
apt-get upgrade
apt-get apt-get install -y build-essential git
#exit 
#leave conteiner
